quil_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: QUILUserBundle:Default:index }


quil_user_idex:
    path:     /user/index
    defaults: { _controller: QUILUserBundle:User:index }

quil_user_add:
    path:     /user/add
    defaults: { _controller: QUILUserBundle:User:add }

quil_user_edit:
    path:     /user/edit/(id)
    defaults: { _controller: QUILUserBundle:User:edit }

quil_user_view:
    path:     /user/view/(id)
    defaults: { _controller: QUILUserBundle:User:view }

quil_user_delete:
    path:     /user/delete/(id)
    defaults: { _controller: QUILUserBundle:User:delete }
